theme: jekyll-theme-hacker
show_downloads: true

# google_analytics:[Your Google Analytics tracking ID]

# Name of website
title: Discovering and Locating Wireless Sensors thru Transmitted Signals
description: Project for UCLA ECEM202A/CSM213A (Fall 2024)
